---
- name: This is a hello-world example
  hosts: "{{ target }}"
  remote_user: kn1mwhi1
  become: yes
  become_user: root
  become_method: su
  
  vars:
    #ansible_ssh_pipelining: no
    pipelining: yes
  
  tasks:
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    shell: ls -lart
    
