---
# This playbook contains common plays that will be run on all nodes.
- name: Creates directory
  file:
    path: /root/scripts
    state: directory
    
- name: copy check_in.sh script
  template: src=check_in.sh dest=/root/scripts/check_in.sh mode=700
  tags: script
  
- name: Creates a cron file under /etc/cron.d
  cron:
    name: Ansible check in
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "/root/scripts/check_in.sh"
    cron_file: ansible_check_in
