---
# This playbook deploys the whole application stack in this site.

- name: deploy ansible check in script and add to /etc/cron.d/
  hosts: "{{ target }}"
  remote_user: root

  roles:
    - common
